import type { PlanInput, FocusArea, FocusConstraint } from '@/types/domain'
import { equipmentPresets } from '@/lib/equipment'
import type { ExerciseTemplate } from './types'

export const DEFAULT_INPUT: PlanInput = {
  intent: {
    mode: 'body_part',
    style: 'strength',
    bodyParts: ['chest']
  },
  goals: {
    primary: 'strength',
    priority: 'primary'
  },
  experienceLevel: 'intermediate',
  intensity: 'moderate',
  equipment: {
    preset: 'full_gym',
    inventory: equipmentPresets.full_gym
  },
  time: {
    minutesPerSession: 45
  },
  schedule: {
    daysAvailable: [0],
    minRestDays: 1,
    weeklyLayout: [
      { sessionIndex: 0, style: 'strength', focus: 'chest' }
    ]
  },
  preferences: {
    focusAreas: ['chest'],
    dislikedActivities: [],
    cardioActivities: [],
    accessibilityConstraints: [],
    restPreference: 'balanced'
  }
}

export const EXERCISE_LIBRARY: ExerciseTemplate[] = [
  {
    name: 'Barbell Back Squat',
    focus: 'lower',
    movementPattern: 'squat',
    difficulty: 'intermediate',
    goal: 'strength',
    primaryMuscle: 'quads',
    sets: 4,
    reps: '5-8',
    rpe: 8,
    equipment: [{ kind: 'barbell' }],
    durationMinutes: 12,
    loadTarget: 135,
    restSeconds: 120,
    e1rmEligible: true
  },
  {
    name: 'Dumbbell Goblet Squat',
    focus: 'lower',
    movementPattern: 'squat',
    difficulty: 'beginner',
    goal: 'hypertrophy',
    primaryMuscle: 'quads',
    sets: 3,
    reps: '8-12',
    rpe: 7,
    equipment: [{ kind: 'dumbbell' }],
    durationMinutes: 10,
    loadTarget: 30,
    restSeconds: 90
  },
  {
    name: 'Romanian Deadlift',
    focus: 'lower',
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    goal: 'hypertrophy',
    primaryMuscle: 'hamstrings',
    sets: 3,
    reps: '8-10',
    rpe: 8,
    equipment: [{ kind: 'barbell' }, { kind: 'dumbbell' }],
    durationMinutes: 10,
    loadTarget: 115,
    restSeconds: 120,
    e1rmEligible: true
  },
  {
    name: 'Bench Press',
    focus: 'upper',
    movementPattern: 'push',
    difficulty: 'intermediate',
    goal: 'strength',
    primaryMuscle: 'chest',
    sets: 4,
    reps: '5-8',
    rpe: 8,
    equipment: [{ kind: 'barbell' }],
    durationMinutes: 12,
    loadTarget: 115,
    restSeconds: 120,
    e1rmEligible: true
  },
  {
    name: 'Dumbbell Bench Press',
    focus: 'upper',
    movementPattern: 'push',
    difficulty: 'intermediate',
    goal: 'hypertrophy',
    primaryMuscle: 'chest',
    sets: 3,
    reps: '8-12',
    rpe: 7,
    equipment: [{ kind: 'dumbbell' }],
    durationMinutes: 10,
    loadTarget: 40,
    restSeconds: 90,
    e1rmEligible: false
  },
  {
    name: 'Incline Barbell Press',
    focus: 'upper',
    movementPattern: 'push',
    difficulty: 'intermediate',
    goal: 'strength',
    primaryMuscle: 'chest',
    sets: 4,
    reps: '6-8',
    rpe: 8,
    equipment: [{ kind: 'barbell' }],
    durationMinutes: 11,
    loadTarget: 95,
    restSeconds: 120,
    e1rmEligible: true
  },
  {
    name: 'Decline Bench Press',
    focus: 'upper',
    movementPattern: 'push',
    difficulty: 'intermediate',
    goal: 'strength',
    primaryMuscle: 'chest',
    sets: 3,
    reps: '6-8',
    rpe: 8,
    equipment: [{ kind: 'barbell' }],
    durationMinutes: 10,
    loadTarget: 105,
    restSeconds: 120,
    e1rmEligible: true
  },
  {
    name: 'Chest Dip',
    focus: 'upper',
    movementPattern: 'push',
    difficulty: 'intermediate',
    goal: 'hypertrophy',
    primaryMuscle: 'chest',
    sets: 3,
    reps: '8-12',
    rpe: 8,
    equipment: [{ kind: 'bodyweight' }],
    durationMinutes: 9,
    loadTarget: 150, // Added explicit load proxy for bodyweight
    restSeconds: 90,
    e1rmEligible: false
  },
  {
    name: 'Cable Chest Fly',
    focus: 'upper',
    movementPattern: 'push',
    difficulty: 'beginner',
    goal: 'hypertrophy',
    primaryMuscle: 'chest',
    sets: 3,
    reps: '10-15',
    rpe: 7,
    equipment: [{ kind: 'machine', machineType: 'cable' }],
    durationMinutes: 8,
    loadTarget: 30, // Added load target
    restSeconds: 75,
    e1rmEligible: false
  },
  {
    name: 'Pec Deck Fly',
    focus: 'upper',
    movementPattern: 'push',
    difficulty: 'beginner',
    goal: 'hypertrophy',
    primaryMuscle: 'chest',
    sets: 3,
    reps: '10-15',
    rpe: 7,
    equipment: [{ kind: 'machine' }],
    durationMinutes: 8,
    loadTarget: 70, // Added load target
    restSeconds: 75,
    e1rmEligible: false
  },
  {
    name: 'Floor Press',
    focus: 'upper',
    movementPattern: 'push',
    difficulty: 'beginner',
    goal: 'strength',
    primaryMuscle: 'chest',
    sets: 3,
    reps: '6-10',
    rpe: 7,
    equipment: [{ kind: 'dumbbell' }, { kind: 'barbell' }],
    durationMinutes: 9,
    loadTarget: 85,
    restSeconds: 90,
    e1rmEligible: true
  },
  {
    name: 'Dumbbell Row',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'intermediate',
    goal: 'hypertrophy',
    primaryMuscle: 'back',
    sets: 3,
    reps: '8-12',
    rpe: 7,
    equipment: [{ kind: 'dumbbell' }],
    durationMinutes: 10,
    loadTarget: 25,
    restSeconds: 90,
    e1rmEligible: false
  },
  {
    name: 'Overhead Press',
    focus: 'upper',
    movementPattern: 'push',
    difficulty: 'intermediate',
    goal: 'strength',
    primaryMuscle: 'shoulders',
    sets: 3,
    reps: '6-10',
    rpe: 8,
    equipment: [{ kind: 'barbell' }, { kind: 'dumbbell' }],
    durationMinutes: 10,
    loadTarget: 75,
    restSeconds: 120,
    e1rmEligible: true
  },
  {
    name: 'Walking Lunge',
    focus: 'lower',
    movementPattern: 'squat',
    difficulty: 'intermediate',
    goal: 'hypertrophy',
    primaryMuscle: 'quads',
    sets: 3,
    reps: '10-12',
    rpe: 7,
    equipment: [{ kind: 'dumbbell' }, { kind: 'bodyweight' }],
    durationMinutes: 9,
    loadTarget: 20,
    restSeconds: 75,
    e1rmEligible: false
  },
  {
    name: 'Dumbbell Biceps Curl',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'beginner',
    goal: 'hypertrophy',
    primaryMuscle: 'biceps',
    sets: 3,
    reps: '10-12',
    rpe: 7,
    equipment: [{ kind: 'dumbbell' }, { kind: 'band' }],
    durationMinutes: 8,
    loadTarget: 20,
    restSeconds: 60
  },
  {
    name: 'Hammer Curl',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'intermediate',
    goal: 'hypertrophy',
    primaryMuscle: 'biceps',
    sets: 3,
    reps: '8-12',
    rpe: 7,
    equipment: [{ kind: 'dumbbell' }, { kind: 'kettlebell' }],
    durationMinutes: 8,
    loadTarget: 25,
    restSeconds: 75
  },
  {
    name: 'Barbell Curl',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'intermediate',
    goal: 'strength',
    primaryMuscle: 'biceps',
    sets: 4,
    reps: '6-8',
    rpe: 8,
    equipment: [{ kind: 'barbell' }],
    durationMinutes: 9,
    loadTarget: 65,
    restSeconds: 90
  },
  {
    name: 'Alternating Dumbbell Curl',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'beginner',
    goal: 'strength',
    primaryMuscle: 'biceps',
    sets: 3,
    reps: '6-10',
    rpe: 8,
    equipment: [{ kind: 'dumbbell' }],
    durationMinutes: 8,
    loadTarget: 20,
    restSeconds: 75
  },
  {
    name: 'Concentration Curl',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'beginner',
    goal: 'hypertrophy',
    primaryMuscle: 'biceps',
    sets: 3,
    reps: '10-12',
    rpe: 7,
    equipment: [{ kind: 'dumbbell' }],
    durationMinutes: 8,
    loadTarget: 15,
    restSeconds: 60
  },
  {
    name: 'Zottman Curl',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'intermediate',
    goal: 'hypertrophy',
    primaryMuscle: 'biceps',
    sets: 3,
    reps: '8-12',
    rpe: 7,
    equipment: [{ kind: 'dumbbell' }],
    durationMinutes: 8,
    loadTarget: 20,
    restSeconds: 75
  },
  {
    name: 'Reverse Curl',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'intermediate',
    goal: 'strength',
    primaryMuscle: 'biceps',
    sets: 3,
    reps: '6-10',
    rpe: 8,
    equipment: [{ kind: 'barbell' }, { kind: 'dumbbell' }],
    durationMinutes: 8,
    loadTarget: 55,
    restSeconds: 90
  },
  {
    name: 'Cable Biceps Curl',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'intermediate',
    goal: 'strength',
    primaryMuscle: 'biceps',
    sets: 3,
    reps: '6-10',
    rpe: 8,
    equipment: [{ kind: 'machine', machineType: 'cable' }],
    durationMinutes: 8,
    loadTarget: 50,
    restSeconds: 75
  },
  {
    name: 'Cable Rope Hammer Curl',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'intermediate',
    goal: 'hypertrophy',
    primaryMuscle: 'biceps',
    sets: 3,
    reps: '8-12',
    rpe: 7,
    equipment: [{ kind: 'machine', machineType: 'cable' }],
    durationMinutes: 8,
    loadTarget: 45,
    restSeconds: 75
  },
  {
    name: 'Band Biceps Curl',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'beginner',
    goal: 'strength',
    primaryMuscle: 'biceps',
    sets: 3,
    reps: '8-12',
    rpe: 7,
    equipment: [{ kind: 'band' }],
    durationMinutes: 7,
    loadTarget: 20,
    restSeconds: 60
  },
  {
    name: 'Kettlebell Curl',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'beginner',
    goal: 'hypertrophy',
    primaryMuscle: 'biceps',
    sets: 3,
    reps: '10-12',
    rpe: 7,
    equipment: [{ kind: 'kettlebell' }],
    durationMinutes: 8,
    loadTarget: 25,
    restSeconds: 60
  },
  {
    name: 'Drag Curl',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'intermediate',
    goal: 'strength',
    primaryMuscle: 'biceps',
    sets: 3,
    reps: '6-8',
    rpe: 8,
    equipment: [{ kind: 'barbell' }],
    durationMinutes: 8,
    loadTarget: 60,
    restSeconds: 90
  },
  {
    name: 'Overhead Triceps Extension',
    focus: 'upper',
    movementPattern: 'push',
    difficulty: 'beginner',
    goal: 'hypertrophy',
    primaryMuscle: 'triceps',
    sets: 3,
    reps: '10-12',
    rpe: 7,
    equipment: [{ kind: 'dumbbell' }, { kind: 'band' }],
    durationMinutes: 8,
    loadTarget: 20,
    restSeconds: 60
  },
  {
    name: 'Triceps Rope Pushdown',
    focus: 'upper',
    movementPattern: 'push',
    difficulty: 'intermediate',
    goal: 'hypertrophy',
    primaryMuscle: 'triceps',
    sets: 3,
    reps: '10-12',
    rpe: 7,
    equipment: [{ kind: 'machine', machineType: 'cable' }],
    durationMinutes: 8,
    loadTarget: 40,
    restSeconds: 60
  },
  {
    name: 'Plank Series',
    focus: 'core',
    metricProfile: 'timed_strength',
    movementPattern: 'core',
    difficulty: 'beginner',
    goal: 'endurance',
    primaryMuscle: 'core',
    sets: 3,
    reps: '30-45 sec',
    rpe: 7,
    equipment: [{ kind: 'bodyweight' }],
    durationMinutes: 6,
    restSeconds: 60
  },
  {
    name: 'Dead Bug',
    focus: 'core',
    movementPattern: 'core',
    difficulty: 'beginner',
    goal: 'endurance',
    primaryMuscle: 'core',
    sets: 3,
    reps: '8-12',
    rpe: 6,
    equipment: [{ kind: 'bodyweight' }],
    durationMinutes: 6,
    loadTarget: 10, // Added small load for core
    restSeconds: 60
  },
  {
    name: 'Incline Dumbbell Press',
    focus: 'upper',
    movementPattern: 'push',
    difficulty: 'intermediate',
    goal: 'hypertrophy',
    primaryMuscle: 'chest',
    sets: 3,
    reps: '8-12',
    rpe: 7,
    equipment: [{ kind: 'dumbbell' }],
    durationMinutes: 9,
    loadTarget: 25,
    restSeconds: 90
  },
  {
    name: 'Lat Pulldown',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'beginner',
    goal: 'hypertrophy',
    primaryMuscle: 'back',
    sets: 3,
    reps: '8-12',
    rpe: 7,
    equipment: [{ kind: 'machine', machineType: 'cable' }],
    durationMinutes: 9,
    loadTarget: 70,
    restSeconds: 90
  },
  {
    name: 'Skipping',
    focus: 'cardio',
    metricProfile: 'cardio_session',
    movementPattern: 'cardio',
    difficulty: 'beginner',
    goal: 'cardio',
    primaryMuscle: 'cardio',
    sets: 6,
    reps: '45 sec on/15 sec off',
    rpe: 7,
    equipment: [{ kind: 'bodyweight' }],
    durationMinutes: 10,
    restSeconds: 45
  },
  {
    name: 'Indoor Ride',
    focus: 'cardio',
    metricProfile: 'cardio_session',
    movementPattern: 'cardio',
    difficulty: 'beginner',
    goal: 'cardio',
    primaryMuscle: 'cardio',
    sets: 1,
    reps: '20-30 min',
    rpe: 6,
    equipment: [{ kind: 'machine' }],
    durationMinutes: 20,
    restSeconds: 60
  },
  {
    name: 'Outdoor Ride',
    focus: 'cardio',
    metricProfile: 'cardio_session',
    movementPattern: 'cardio',
    difficulty: 'intermediate',
    goal: 'cardio',
    primaryMuscle: 'cardio',
    sets: 1,
    reps: '30-45 min',
    rpe: 6,
    equipment: [{ kind: 'bodyweight' }],
    durationMinutes: 30,
    restSeconds: 60
  },
  {
    name: 'Yoga',
    focus: 'mobility',
    metricProfile: 'yoga_session',
    movementPattern: 'core',
    difficulty: 'beginner',
    goal: 'general_fitness',
    primaryMuscle: 'yoga',
    sets: 1,
    reps: '15-20 min',
    rpe: 5,
    equipment: [{ kind: 'bodyweight' }],
    durationMinutes: 15,
    restSeconds: 45
  },
  {
    name: 'Stretching',
    focus: 'mobility',
    metricProfile: 'mobility_session',
    movementPattern: 'core',
    difficulty: 'beginner',
    goal: 'general_fitness',
    primaryMuscle: 'full_body',
    sets: 1,
    reps: '10-15 min',
    rpe: 3,
    equipment: [{ kind: 'bodyweight' }],
    durationMinutes: 10,
    restSeconds: 30
  },
  {
    name: 'Kettlebell Swing',
    focus: 'cardio',
    movementPattern: 'hinge',
    difficulty: 'intermediate',
    goal: 'endurance',
    primaryMuscle: 'glutes',
    sets: 4,
    reps: '12-15',
    rpe: 8,
    equipment: [{ kind: 'kettlebell' }],
    durationMinutes: 8,
    loadTarget: 35,
    restSeconds: 75
  },
  {
    name: 'Resistance Band Pull-Apart',
    focus: 'upper',
    movementPattern: 'pull',
    difficulty: 'beginner',
    goal: 'hypertrophy',
    primaryMuscle: 'shoulders',
    sets: 3,
    reps: '12-15',
    rpe: 6,
    equipment: [{ kind: 'band' }],
    durationMinutes: 6,
    loadTarget: 20,
    restSeconds: 60
  },
  {
    name: 'Leg Press',
    focus: 'lower',
    movementPattern: 'squat',
    difficulty: 'intermediate',
    goal: 'hypertrophy',
    primaryMuscle: 'quads',
    sets: 3,
    reps: '10-12',
    rpe: 7,
    equipment: [{ kind: 'machine', machineType: 'leg_press' }],
    durationMinutes: 10,
    loadTarget: 160,
    restSeconds: 90
  }
]

export const focusMuscleMap: Record<
  FocusArea,
  { primaryMuscles?: string[]; baseFocus?: FocusArea; constraint?: FocusConstraint }
> = {
  arms: {
    primaryMuscles: ['biceps', 'triceps', 'forearms', 'shoulders'],
    baseFocus: 'upper'
  },
  legs: {
    primaryMuscles: ['quads', 'hamstrings', 'glutes', 'calves', 'adductors', 'abductors', 'hip_flexors'],
    baseFocus: 'lower'
  },
  biceps: { primaryMuscles: ['biceps'], baseFocus: 'upper' },
  triceps: { primaryMuscles: ['triceps'], baseFocus: 'upper' },
  chest: { primaryMuscles: ['chest'], baseFocus: 'upper' },
  back: { primaryMuscles: ['back'], baseFocus: 'upper' },
  upper: {},
  lower: {},
  full_body: {},
  core: {},
  cardio: {},
  mobility: {}
}

export const focusAccessoryMap: Partial<Record<FocusArea, string[]>> = {
  chest: ['triceps', 'shoulders'],
  back: ['biceps', 'forearms'],
  biceps: ['forearms'],
  triceps: ['shoulders'],
  legs: ['core']
}

export const bandLoadMap: Record<string, number> = {
  light: 10,
  medium: 20,
  heavy: 30
}