delete from public.exercise_catalog;

insert into public.exercise_catalog (
  name, focus, movement_pattern, difficulty, goal, primary_muscle, secondary_muscles,
  sets, reps, rpe, equipment, duration_minutes, load_target, rest_seconds, metric_profile, e1rm_eligible
) values
('Barbell Back Squat', 'lower', 'squat', 'intermediate', 'strength', 'quads', '{}', 4, '5-8', 8, '[{"kind": "barbell"}]'::jsonb, 12, 135, 120, null, true),
('Dumbbell Goblet Squat', 'lower', 'squat', 'beginner', 'hypertrophy', 'quads', '{}', 3, '8-12', 7, '[{"kind": "dumbbell"}]'::jsonb, 10, 30, 90, null, false),
('Romanian Deadlift', 'lower', 'hinge', 'intermediate', 'hypertrophy', 'hamstrings', '{}', 3, '8-10', 8, '[{"kind": "barbell"}, {"kind": "dumbbell"}]'::jsonb, 10, 115, 120, null, true),
('Bench Press', 'upper', 'push', 'intermediate', 'strength', 'chest', '{}', 4, '5-8', 8, '[{"kind": "barbell"}]'::jsonb, 12, 115, 120, null, true),
('Dumbbell Bench Press', 'upper', 'push', 'intermediate', 'hypertrophy', 'chest', '{}', 3, '8-12', 7, '[{"kind": "dumbbell"}]'::jsonb, 10, 40, 90, null, false),
('Incline Barbell Press', 'upper', 'push', 'intermediate', 'strength', 'chest', '{}', 4, '6-8', 8, '[{"kind": "barbell"}]'::jsonb, 11, 95, 120, null, true),
('Decline Bench Press', 'upper', 'push', 'intermediate', 'strength', 'chest', '{}', 3, '6-8', 8, '[{"kind": "barbell"}]'::jsonb, 10, 105, 120, null, true),
('Chest Dip', 'upper', 'push', 'intermediate', 'hypertrophy', 'chest', '{}', 3, '8-12', 8, '[{"kind": "bodyweight"}]'::jsonb, 9, 150, 90, null, false),
('Cable Chest Fly', 'upper', 'push', 'beginner', 'hypertrophy', 'chest', '{}', 3, '10-15', 7, '[{"kind": "machine", "machineType": "cable"}]'::jsonb, 8, 30, 75, null, false),
('Pec Deck Fly', 'upper', 'push', 'beginner', 'hypertrophy', 'chest', '{}', 3, '10-15', 7, '[{"kind": "machine"}]'::jsonb, 8, 70, 75, null, false),
('Floor Press', 'upper', 'push', 'beginner', 'strength', 'chest', '{}', 3, '6-10', 7, '[{"kind": "dumbbell"}, {"kind": "barbell"}]'::jsonb, 9, 85, 90, null, true),
('Dumbbell Row', 'upper', 'pull', 'intermediate', 'hypertrophy', 'back', '{}', 3, '8-12', 7, '[{"kind": "dumbbell"}]'::jsonb, 10, 25, 90, null, false),
('Overhead Press', 'upper', 'push', 'intermediate', 'strength', 'shoulders', '{}', 3, '6-10', 8, '[{"kind": "barbell"}, {"kind": "dumbbell"}]'::jsonb, 10, 75, 120, null, true),
('Walking Lunge', 'lower', 'squat', 'intermediate', 'hypertrophy', 'quads', '{}', 3, '10-12', 7, '[{"kind": "dumbbell"}, {"kind": "bodyweight"}]'::jsonb, 9, 20, 75, null, false),
('Dumbbell Biceps Curl', 'upper', 'pull', 'beginner', 'hypertrophy', 'biceps', '{}', 3, '10-12', 7, '[{"kind": "dumbbell"}, {"kind": "band"}]'::jsonb, 8, 20, 60, null, false),
('Hammer Curl', 'upper', 'pull', 'intermediate', 'hypertrophy', 'biceps', '{}', 3, '8-12', 7, '[{"kind": "dumbbell"}, {"kind": "kettlebell"}]'::jsonb, 8, 25, 75, null, false),
('Barbell Curl', 'upper', 'pull', 'intermediate', 'strength', 'biceps', '{}', 4, '6-8', 8, '[{"kind": "barbell"}]'::jsonb, 9, 65, 90, null, false),
('Alternating Dumbbell Curl', 'upper', 'pull', 'beginner', 'strength', 'biceps', '{}', 3, '6-10', 8, '[{"kind": "dumbbell"}]'::jsonb, 8, 20, 75, null, false),
('Concentration Curl', 'upper', 'pull', 'beginner', 'hypertrophy', 'biceps', '{}', 3, '10-12', 7, '[{"kind": "dumbbell"}]'::jsonb, 8, 15, 60, null, false),
('Zottman Curl', 'upper', 'pull', 'intermediate', 'hypertrophy', 'biceps', '{}', 3, '8-12', 7, '[{"kind": "dumbbell"}]'::jsonb, 8, 20, 75, null, false),
('Reverse Curl', 'upper', 'pull', 'intermediate', 'strength', 'biceps', '{}', 3, '6-10', 8, '[{"kind": "barbell"}, {"kind": "dumbbell"}]'::jsonb, 8, 55, 90, null, false),
('Cable Biceps Curl', 'upper', 'pull', 'intermediate', 'strength', 'biceps', '{}', 3, '6-10', 8, '[{"kind": "machine", "machineType": "cable"}]'::jsonb, 8, 50, 75, null, false),
('Cable Rope Hammer Curl', 'upper', 'pull', 'intermediate', 'hypertrophy', 'biceps', '{}', 3, '8-12', 7, '[{"kind": "machine", "machineType": "cable"}]'::jsonb, 8, 45, 75, null, false),
('Band Biceps Curl', 'upper', 'pull', 'beginner', 'strength', 'biceps', '{}', 3, '8-12', 7, '[{"kind": "band"}]'::jsonb, 7, 20, 60, null, false),
('Kettlebell Curl', 'upper', 'pull', 'beginner', 'hypertrophy', 'biceps', '{}', 3, '10-12', 7, '[{"kind": "kettlebell"}]'::jsonb, 8, 25, 60, null, false),
('Drag Curl', 'upper', 'pull', 'intermediate', 'strength', 'biceps', '{}', 3, '6-8', 8, '[{"kind": "barbell"}]'::jsonb, 8, 60, 90, null, false),
('Overhead Triceps Extension', 'upper', 'push', 'beginner', 'hypertrophy', 'triceps', '{}', 3, '10-12', 7, '[{"kind": "dumbbell"}, {"kind": "band"}]'::jsonb, 8, 20, 60, null, false),
('Triceps Rope Pushdown', 'upper', 'push', 'intermediate', 'hypertrophy', 'triceps', '{}', 3, '10-12', 7, '[{"kind": "machine", "machineType": "cable"}]'::jsonb, 8, 40, 60, null, false),
('Plank Series', 'core', 'core', 'beginner', 'endurance', 'core', '{}', 3, '30-45 sec', 7, '[{"kind": "bodyweight"}]'::jsonb, 6, null, 60, 'timed_strength', false),
('Dead Bug', 'core', 'core', 'beginner', 'endurance', 'core', '{}', 3, '8-12', 6, '[{"kind": "bodyweight"}]'::jsonb, 6, 10, 60, null, false),
('Incline Dumbbell Press', 'upper', 'push', 'intermediate', 'hypertrophy', 'chest', '{}', 3, '8-12', 7, '[{"kind": "dumbbell"}]'::jsonb, 9, 25, 90, null, false),
('Lat Pulldown', 'upper', 'pull', 'beginner', 'hypertrophy', 'back', '{}', 3, '8-12', 7, '[{"kind": "machine", "machineType": "cable"}]'::jsonb, 9, 70, 90, null, false),
('Skipping', 'cardio', 'cardio', 'beginner', 'cardio', 'cardio', '{}', 6, '45 sec on/15 sec off', 7, '[{"kind": "bodyweight"}]'::jsonb, 10, null, 45, 'cardio_session', false),
('Indoor Ride', 'cardio', 'cardio', 'beginner', 'cardio', 'cardio', '{}', 1, '20-30 min', 6, '[{"kind": "machine"}]'::jsonb, 20, null, 60, 'cardio_session', false),
('Outdoor Ride', 'cardio', 'cardio', 'intermediate', 'cardio', 'cardio', '{}', 1, '30-45 min', 6, '[{"kind": "bodyweight"}]'::jsonb, 30, null, 60, 'cardio_session', false),
('Yoga', 'mobility', 'core', 'beginner', 'general_fitness', 'yoga', '{}', 1, '15-20 min', 5, '[{"kind": "bodyweight"}]'::jsonb, 15, null, 45, 'yoga_session', false),
('Stretching', 'mobility', 'core', 'beginner', 'general_fitness', 'full_body', '{}', 1, '10-15 min', 3, '[{"kind": "bodyweight"}]'::jsonb, 10, null, 30, 'mobility_session', false),
('Kettlebell Swing', 'cardio', 'hinge', 'intermediate', 'endurance', 'glutes', '{}', 4, '12-15', 8, '[{"kind": "kettlebell"}]'::jsonb, 8, 35, 75, null, false),
('Resistance Band Pull-Apart', 'upper', 'pull', 'beginner', 'hypertrophy', 'shoulders', '{}', 3, '12-15', 6, '[{"kind": "band"}]'::jsonb, 6, 20, 60, null, false),
('Leg Press', 'lower', 'squat', 'intermediate', 'hypertrophy', 'quads', '{}', 3, '10-12', 7, '[{"kind": "machine", "machineType": "leg_press"}]'::jsonb, 10, 160, 90, null, false);
